import type { Device } from './types';

const fmt=(n:number)=>n.toLocaleString();
const clean=(v:string|null|undefined)=>v?.trim()||'Unknown';
const pct=(n:number,total:number)=>total?`${(n/total*100).toFixed(1)}%`:'0.0%';
function countValues(values:string[]){return Object.entries(values.reduce<Record<string,number>>((a,v)=>{a[v]=(a[v]??0)+1;return a},{})).sort((a,b)=>b[1]-a[1])}
function rawValue(device:Device,patterns:RegExp[]){for(const [name,value] of Object.entries(device.raw)){if(patterns.some(p=>p.test(name))&&value?.trim())return value.trim()}return ''}
function hardwareType(device:Device){if(device.platform==='ios')return'Smartphone';if(device.platform==='ipados')return'Tablet';const explicit=rawValue(device,[/chassis/i,/form.?factor/i,/device.?type/i,/hardware.?type/i]).toLowerCase();const model=(device.model||'').toLowerCase();const signal=`${explicit} ${model} ${(device.manufacturer||'').toLowerCase()}`;if(/virtual|vmware|hyper-v|horizon|avd/.test(signal))return'Virtual';if(device.platform==='android')return /tablet|pixel tablet|galaxy tab|tab active/.test(signal)?'Tablet':'Smartphone';if(device.platform==='macos'){if(/macbook/.test(signal))return'Laptop';if(/imac|mac mini|mac studio|mac pro/.test(signal))return'Desktop'}if(/surface pro|surface go|tablet|slate/.test(signal))return'Tablet';if(/laptop|notebook|latitude|thinkpad|thinkbook|elitebook|probook|zbook|surface laptop|dell pro 1[346]|macbook/.test(signal))return'Laptop';if(/desktop|tower|micro|mini|sff|optiplex|thinkcentre|prodesk|elitedesk|surface studio/.test(signal))return'Desktop';return'Unknown'}
function platformGroup(d:Device){return d.platform==='ios'||d.platform==='ipados'?'Apple Mobile':d.platform==='windows'?'Windows':d.platform==='android'?'Android':d.platform==='macos'?'macOS':d.platform==='linux'?'Linux':'Unknown'}

export function OperatingSystemInsights({devices}:{devices:Device[]}){const total=devices.length;const groups=Object.entries(devices.reduce<Record<string,Device[]>>((a,d)=>{const k=platformGroup(d);(a[k]??=[]).push(d);return a},{})).sort((a,b)=>b[1].length-a[1].length);return <section className="extendedInsightGrid categorizedInsightGrid"><Card title="OS & platform distribution" subtitle="Platforms grouped for operational reporting"><Distribution rows={groups.map(([p,list])=>[p,list.length] as [string,number])} total={total}/></Card><Card title="OS fragmentation" subtitle="Version diversity and dominant release per platform"><div className="fragmentationList">{groups.map(([platform,list])=>{const versions=countValues(list.map(d=>clean(d.osVersion))),top=versions[0];return <div key={platform}><header><strong>{platform}</strong><span>{versions.length} version{versions.length===1?'':'s'}</span></header><div><span className="truncate">{top?.[0]||'Unknown'}</span><b>{pct(top?.[1]||0,list.length)} on top version</b></div><i><b style={{width:pct(top?.[1]||0,list.length)}}/></i></div>})}</div></Card></section>}

export function HardwareInsights({devices}:{devices:Device[]}){const total=devices.length;const types=countValues(devices.map(hardwareType));const manufacturers=countValues(devices.map(d=>clean(d.manufacturer))).filter(([v])=>v!=='Unknown');const models=countValues(devices.map(d=>clean(d.model))).filter(([v])=>v!=='Unknown');const top10=models.slice(0,10).reduce((s,[,n])=>s+n,0);const singletons=models.filter(([,n])=>n===1).length;return <section className="extendedInsightGrid categorizedInsightGrid"><Card title="Hardware type" subtitle="Laptop, desktop, smartphone, tablet and other form factors"><Distribution rows={types} total={total}/></Card><Card title="Hardware manufacturers" subtitle="Largest hardware vendors in the current inventory"><Distribution rows={manufacturers.slice(0,8)} total={total}/></Card><Card title="Hardware models" subtitle="Most common reported models"><Distribution rows={models.slice(0,8)} total={total}/></Card><Card title="Hardware standardization" subtitle="How concentrated the fleet is around common models"><div className="metricTiles"><Metric label="Unique models" value={fmt(models.length)}/><Metric label="Top 10 coverage" value={pct(top10,total)}/><Metric label="One-off models" value={fmt(singletons)}/></div><div className="miniBars">{models.slice(0,6).map(([m,n])=><div key={m}><span className="truncate">{m}</span><strong>{fmt(n)}</strong><i><b style={{width:pct(n,models[0]?.[1]||1)}}/></i></div>)}</div></Card></section>}

export function ManagementInsights({devices}:{devices:Device[]}){const total=devices.length;const ownership=countValues(devices.map(d=>clean(d.ownership)));const users=countValues(devices.map(d=>clean(d.userUpn||d.userDisplayName)).filter(v=>v!=='Unknown'));const noUser=devices.filter(d=>!d.userUpn&&!d.userDisplayName).length;return <section className="extendedInsightGrid categorizedInsightGrid"><Card title="Ownership" subtitle="Corporate, personal and other ownership states"><Distribution rows={ownership} total={total}/></Card><Card title="Devices per user" subtitle="Managed-device density across identified users"><div className="metricTiles"><Metric label="1 device" value={fmt(users.filter(([,n])=>n===1).length)}/><Metric label="2 devices" value={fmt(users.filter(([,n])=>n===2).length)}/><Metric label="3+ devices" value={fmt(users.filter(([,n])=>n>=3).length)}/></div><div className="inlineInsight"><span>No primary user</span><strong>{fmt(noUser)}</strong><small>{pct(noUser,total)} of devices</small></div></Card></section>}

function Card({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <article className="dashboardCard extendedInsightCard"><header className="dashboardCardHead"><div><h2>{title}</h2><p>{subtitle}</p></div></header>{children}</article>}
function Distribution({rows,total}:{rows:[string,number][];total:number}){return <div className="distributionList">{rows.filter(([,n])=>n>0).slice(0,8).map(([label,n],i)=><div key={label}><span className={`distributionDot dot${i%6}`}/><span className="truncate" title={label}>{label}</span><strong>{fmt(n)}</strong><small>{pct(n,total)}</small><i><b style={{width:pct(n,total)}}/></i></div>)}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metricTile"><span>{label}</span><strong>{value}</strong></div>}
