export default function LandingContent(){return <div className="landingStory">
<section className="storyIntro"><span>FROM EXPORT TO INSIGHT</span><h2>More than a device list.</h2><p>Native Intune inventory contains valuable information, but cross-platform exploration, drill-down and management-ready views can take work. The Analyzer turns a standard export into an interactive local workspace.</p></section>
<section className="storySteps"><Story n="01" title="Export from Intune" text="Create a native device inventory export in Microsoft Intune. ZIP and CSV are supported."/><Story n="02" title="Analyze locally" text="Drop the export into the browser. Parsing, normalization and analysis happen on your device."/><Story n="03" title="Explore and drill down" text="Move from fleet health and security signals to the exact devices behind a metric."/><Story n="04" title="Report what matters" text="Prepare focused exports and presentation-ready management information from the same inventory."/></section>
<section className="featureShowcase"><div className="showcaseCopy"><span>BUILT FOR REAL INVENTORIES</span><h2>One inventory. Multiple perspectives.</h2><p>Switch from overall fleet health to platform-specific analysis, then drill into devices, update position, hardware and actionable attention points.</p><div className="showcaseTags"><b>Health & security</b><b>Device Intelligence</b><b>Hardware insights</b><b>Local exports</b></div></div><div className="showcaseVisual"><div className="mockTop"><i/><i/><i/></div><div className="mockKpis"><b/><b/><b/></div><div className="mockChart"><span/><span/><span/><span/></div></div></section>
<section className="privacyFeature"><div className="privacyMark">✓</div><div><span>PRIVATE BY DESIGN</span><h2>Your inventory stays under your control.</h2><p>The application does not upload or persist your Intune inventory. The file is read and analyzed locally in your browser. Reload the application and the inventory is gone.</p></div><a href="https://github.com/roryvossepoel/Intune-Device-Inventory-Analyzer" target="_blank" rel="noreferrer">View source on GitHub ↗</a></section>
<section className="landingFaq" id="faq"><header><span>FAQ</span><h2>Questions about the Analyzer</h2><p>How it works, why it exists and what happens to your data.</p></header><div className="faqGrid"><Faq q="Why does this dashboard exist?">Microsoft Intune provides extensive inventory data, but exploring relationships, drilling from high-level insights to individual devices and creating management views can require additional reporting. This project provides a focused exploration layer for native Intune exports.</Faq><Faq q="Is my Intune data uploaded or stored?">No. Inventory processing happens locally in your browser. The Analyzer does not send your device or user inventory to a backend service and does not persist the loaded export.</Faq><Faq q="How do I use it?">Create a device inventory export in Intune and open the resulting ZIP or CSV file here. The application normalizes the export and builds the dashboard locally.</Faq><Faq q="Is this project open source?">Yes. The source code is public. You can review it, download it, fork it and adapt the Analyzer for your own requirements.</Faq><Faq q="Can I suggest a feature or contribute?">Absolutely. Suggestions, data mappings, platform intelligence and code contributions can be submitted through GitHub.</Faq><Faq q="Can I use it for management reporting?">That is one of the goals. The Reports area is being designed for focused data exports and reusable presentation-ready visuals based on the inventory you loaded.</Faq></div></section>
</div>}
function Story({n,title,text}:{n:string;title:string;text:string}){return <article><span>{n}</span><h3>{title}</h3><p>{text}</p></article>}
function Faq({q,children}:{q:string;children:React.ReactNode}){return <details><summary>{q}<span>+</span></summary><p>{children}</p></details>}
