import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './AppV2';
import './base.css';
import './landing.css';
import './dashboard.css';
import './workspace.css';
import './header.css';
import './branding-logo.css';
import './insights.css';
import './table.css';
import './typography.css';
import './extended-insights.css';
import './dashboard-cleanup.css';
import './update-health.css';
import './dashboard-design-system.css';
import './navigation-v2.css';
import './platform-context.css';
import './device-explorer.css';
import './security-insights.css';
import './dashboard-sections.css';
import './dashboard-v2.css';
import './inventory-activity.css';
import './hardware-polish.css';
import './hardware-expand.css';
import './hardware-expand';
import './hardware-summary.css';
import './hardware-summary';
import './percentage-polish';
import './landing-story.css';
import './faq.css';
import './homepage-polish.css';
import './device-header-simplify.css';
import './device-table-layout.css';
import './search-polish.css';
import './active-filter-state.css';
import './device-ux-polish.css';
import './hardware-explorer-filters.css';
import './hardware-filter-context';
import './device-detail-v2.css';
import './platform-intelligence-v2.css';
import './sticky-device-header.css';
import './reorderable-columns.css';
import './slider-scale.css';
import './column-resize-v2.css';
import './windows-lifecycle.css';
import './sticky-device-header';
import './column-resize-v2';
import './inventory-activity-polish';
import './health-security-final-polish.css';
import './header-reference.css';
import './device-filter-collapse-fix.css';
import './header-reference';
import './dashboard-unity-polish.css';
import './mobile-hardware-icon-fix.css';
import './mobile-hardware-unity.css';
import './users-ownership.css';
import './product-refresh.css';
import './homepage-final-polish.css';
import './typography-background-polish.css';
import './homepage-readable-v2.css';
import './brand-home';
import './header-height-polish.css';
import './homepage-body-polish.css';
import './homepage-card-variants.css';
import './homepage-scroll-reveal.css';
import './homepage-scroll-reveal';
import './mobile-navigation.css';
import './mobile-navigation-primary-tabs.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
